// Generated by scripts/sync-android.mjs in CasaZapp-tv from the web app's design. Do not edit.
package nl.casazapp.tv.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import nl.casazapp.tv.R

/** Colours: apps/web/src/styles.css. */
object Casa {
    val bg = Color(0xFF080C11)
    val surface = Color(0xFF10161F)
    val raised = Color(0xFF171F2B)
    val line = Color(0xFF232E3F)
    val text = Color(0xFFE8EDF4)
    val muted = Color(0xFF8793A6)
    val accent = Color(0xFFFFB547)
    val accentInk = Color(0xFF1C1305)
    val live = Color(0xFFFF4D5E)
    val ok = Color(0xFF3DD68C)
}

/** Fonts: Sora for headings, Figtree for text, IBM Plex Mono for numbers and times. */
object CasaFonts {
    val display = FontFamily(Font(R.font.sora_400, FontWeight(400)), Font(R.font.sora_600, FontWeight(600)), Font(R.font.sora_700, FontWeight(700)))
    val sans = FontFamily(Font(R.font.figtree_400, FontWeight(400)), Font(R.font.figtree_500, FontWeight(500)), Font(R.font.figtree_600, FontWeight(600)), Font(R.font.figtree_700, FontWeight(700)))
    val mono = FontFamily(Font(R.font.plex_mono_400, FontWeight(400)), Font(R.font.plex_mono_500, FontWeight(500)))
}

/** Icon paths: apps/web/src/ui.tsx, 24×24 strokes. */
object IconPaths {
    const val home = "M3 10.5 12 3l9 7.5V20a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"
    const val tv = "M5 6h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2zM8 2l4 4 4-4"
    const val film = "M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zM7 3v18M17 3v18M3 8h4M3 16h4M17 8h4M17 16h4M3 12h18"
    const val series = "M5 7h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2zM6 4h12"
    const val list = "M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"
    const val settings = "M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM19.4 15l1.6 1.2-2 3.4-1.9-.7a7 7 0 0 1-2 1.2L14.8 22h-4l-.3-1.9a7 7 0 0 1-2-1.2l-1.9.7-2-3.4L6.2 15a7 7 0 0 1 0-2.4L4.6 11.4l2-3.4 1.9.7a7 7 0 0 1 2-1.2L10.8 5.6h4l.3 1.9a7 7 0 0 1 2 1.2l1.9-.7 2 3.4-1.6 1.2a7 7 0 0 1 0 2.4z"
    const val out = "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9"
    const val back = "M15 18l-6-6 6-6"
    const val up = "m18 15-6-6-6 6"
    const val down = "m6 9 6 6 6-6"
    const val search = "M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14zM21 21l-4.3-4.3"
    const val play = "M6 4v16l14-8z"
    const val close = "M18 6 6 18M6 6l12 12"
    const val volume = "M11 5 6 9H3v6h3l5 4zM15.5 8.5a5 5 0 0 1 0 7M18.5 5.5a9 9 0 0 1 0 13"
    const val muted = "M11 5 6 9H3v6h3l5 4zM22 9l-6 6M16 9l6 6"
    const val fullscreen = "M8 3H5a2 2 0 0 0-2 2v3M21 8V5a2 2 0 0 0-2-2h-3M3 16v3a2 2 0 0 0 2 2h3M16 21h3a2 2 0 0 0 2-2v-3"
    const val exitFullscreen = "M8 3v3a2 2 0 0 1-2 2H3M21 8h-3a2 2 0 0 1-2-2V3M3 16h3a2 2 0 0 1 2 2v3M16 21v-3a2 2 0 0 1 2-2h3"
    const val audio = "M4 10v4M8 6v12M12 3v18M16 8v8M20 11v2"
    const val subtitles = "M5 5h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2zM7 13h4M13 13h4M7 16h10"
    const val check = "M20 6 9 17l-5-5"
    const val star = "m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3l-5.6 2.9 1.1-6.2L3 9.6l6.2-.9z"
    const val edit = "M4 20h4L19 9l-4-4L4 16zM13.5 6.5l4 4"
    const val swap = "M4 8h14l-4-4M20 16H6l4 4"
    const val guide = "M4 5h16v14H4zM4 10h16M9 10v9"
    const val rotate = "M3 12a9 9 0 1 0 3-6.7L3 8M3 3v5h5"
    const val android = "M6 10a6 6 0 0 1 12 0v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1zM8 4.5 9.5 6.5M16 4.5l-1.5 2M9.5 13h.01M14.5 13h.01M9 18v3M15 18v3M3.5 11v5M20.5 11v5"
    const val download = "M12 3v12M7 10l5 5 5-5M5 21h14"
}
